default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
- hooks:
  - id: black
    args: [-t, py27]
  repo: https://github.com/ambv/black
  rev: 19.10b0
- hooks:
  - id: isort
  repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
