- id: mbeautify
  name: mbeautify
  description: '`mbeautify` is a command-line utility for enforcing style consistency across Matlab projects.'
  entry: mbeautify
  language: python
  additional_dependencies: [argopt, requests, tqdm]
  types: [text]
  files: \.(m)$
  require_serial: true
